name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint || echo "Lint warnings ignored"

      - name: Run Tests
        run: npm test || echo "No tests found"

      - name: Build
        run: npm run build

      - name: Backend Deploy
        if: success()
        run: |
          curl "$RENDER_DEPLOY_HOOK_API"

      - name: Frontend Deploy
        if: success()
        run: |
          curl "$RENDER_DEPLOY_HOOK_CLIENT"
